# Generated by Django 4.1.4 on 2023-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projects_id_alter_projects_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
