# Generated by Django 4.1.3 on 2023-01-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projects_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(default='uhkdn jhdukjdh jkdhaskjakj kjhadakjdsh jkdedjh kjfhakdjhdjhfu jkhfeksjfhd jhfdkjfhsdkj jkdfhesfkjshdksjfh jkdhfskdjfhdfk jkfhskjfdh jkdfhsdkjfhd kjer hkjhfskdjc'),
        ),
    ]
