# Generated by Django 4.1.3 on 2023-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ispopolar',
            field=models.BooleanField(default=True),
        ),
    ]
