# Generated by Django 4.1.3 on 2023-01-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.CharField(max_length=200),
        ),
    ]
